application: ming-xiao-123
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /
  script: main.app

- url: /stylesheets
  static_dir: stylesheets


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: MySQLdb
  version: latest